### ISSUE TITLE
Permutation tests for CCA

### ISSUE THREAD

**Issue by LegrandNico** [jameschapman19/cca_zoo#124]
I would like to implement (if not already available elsewhere) a Python version of the permutation tests for CCA described in

> Winkler AM, Renaud O, Smith SM, Nichols TE. Permutation Inference for Canonical Correlation Analysis. NeuroImage. 2020; 117065 (see article [here](https://www.sciencedirect.com/science/article/pii/S1053811920305516))

The paper comes with a [repository](https://github.com/andersonwinkler/PermCCA) (Matlab) that could be ported to Python without requiring additional dependencies.

**Comment by jameschapman19** [comment]
Funny you mention this as it's something vaguely on my radar (that I took off the boil)! 

I actually made a start porting the quickperms from the PALM toolbox (with the permission of Winkler/Smith) here: https://github.com/jameschapman19/scikit-perm/blob/main/skperm/permutation_tests/cca_permutation_test.py

Which would be a nice bonus with a ported version of permCCA (i.e. where the user can supply their own permutations based on exchangeability blocks).

**Comment by htwangtw** [comment]
I got code for the full implementation in python.

**Comment by LegrandNico** [comment]
Thank you @htwangtw , I think that will be really helpful.

I don't know how you want to integrate the permutation functionalities with the rest of the package. I can try to make something, but maybe will start with an example tutorial notebook see if we have everything running.

**Comment by jameschapman19** [comment]
I would guess you could adapt @htwangtw's code to look something like https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.permutation_test_score.html

Could be rudimentary initially with the goal to get close to sklearn API which could run permutation tests in parallel

**Comment by JohannesWiesner** [comment]
Just for completeness: There are two other packages that might also help?

The pyls package has implemented permutation tests:
https://pyls.readthedocs.io/en/latest/index.html

And there's also the resample package:
https://github.com/resample-project/resample

**Comment by jameschapman19** [comment]
I've put a version of this in cca_zoo.model_selection._validation with an API that hooks into scikit-learn permutation_test_score.

It's not quite the same as what Winkler does for multiple latent dimensions (but it should be similar) but it works for 1 latent dimension. Should be able to build on this.

**Comment by jameschapman19** [comment]
I'll add a proper example but it should work like:

```
from cca_zoo.model_selection import permutation_test_score
from cca_zoo.models import rCCA
import numpy as np

X = np.random.rand(100, 10)
Y = np.random.rand(100, 8)
model = rCCA(c=[0.1, 0.3])

permutation_test_score(model, [X, Y], n_permutations=10)
```

**Comment by WantongLi123** [comment]
Although I got a lot insights from your nice discussion here, one thing I am still confused:
If I permute one variable once from all views (variable number: 1), or if I permute 1/5 of total variables in all views (variable number: around 10), the resulted significance p value is very different. 

It's understandable that when permuting more variables, the random level is high, so that the canonical correlation coefficient is low compared to the reference experiment.
But do you know permuting how many variables is common? And permutation should be done for each view once or multiple views?

Many thanks in advance!

Cheers,
Wantong
