### ISSUE TITLE
Not able to run examples 

### ISSUE THREAD

**Issue by amogh3892** [jameschapman19/cca_zoo#132]
I installed both the below 

pip install cca-zoo
pip install ccc-zoo[deep]

and I am trying to run the example in the link below 
https://cca-zoo.readthedocs.io/en/latest/auto_examples/plot_dcca.html#sphx-glr-auto-examples-plot-dcca-py

I am getting an error 
(ImportError: cannot import name 'Split_MNIST_Dataset')
But I am able to import Tangled_MNIST_dataset 

By executing "dir(cca_zoo)", I get the following 
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'cca_zoo', 'data', 'deepmodels', 'models', 'utils']

Has Split_MNIST_Dataset been removed ? 

Also there are several other functions not available. 
For ex "dir(cca_zoo.deepmodels)", gives 

['DCCA', 'DCCAE', 'DCCA_NOI', 'DTCCA', 'DVCCA', 'DeepWrapper', 'SplitAE', '_DCCA_base', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_dcca_base', 'architectures', 'cca_zoo', 'dcca', 'dcca_noi', 'dccae', 'deepwrapper', 'dtcca', 'dvcca', 'objectives', 'splitae']

So I cannot find "CCALightning", "get_dataloaders" etc. 

I am currently using the following versions 
PyTorch: Version: 1.10.2
PyTorch-lighning: Version: 1.5.9
cca-zoo: Version: 1.7.13

Please help with this and please let me know if anything has been changed within the versions. 
Thank you in advance for the help.

**Comment by jameschapman19** [comment]
Yeah I assume there's no specific reason you're on the v1.7.13? If not then upgrading to the current version should fix these (since they run latest version on the docs)

Was a substantial change after 1.7 to use lightning for everything. Everything is now somewhat stable in the sense that I won't drastically change the API anymore :)

**Comment by amogh3892** [comment]
Hello, 

Thank you for the quick response. No matter how hard I tried, the last version I was able to obtain was 1.7.13 (I thought that was the latest version). I was using python 3.6.10. I guess it doesn't work on that. I was able to install 1.10.10 on python 3.8. Thank you for pointing it out.

**Comment by jameschapman19** [comment]
Ah thank you for pointing out python version compatibility! I test 3.7/8/9 but you're right that that's not indicated anywhere so will leave this issue until I update the docs :)
