### ISSUE TITLE
Remove unused "y" parameter from CCA methods?

### ISSUE THREAD

**Issue by LegrandNico** [jameschapman19/cca_zoo#137]
Most of the methods associated with the CCA classes accept a `y=None` parameter that does not appear to be used elsewhere in the code (e.g [here](https://github.com/jameschapman19/cca_zoo/blob/16f712aad2c79c8f911fcb9741e1220691249a28/cca_zoo/models/_cca_base.py#L80)) and that is not documented in the docstring.

If I am reading it correctly, it looks like this parameter could be removed from most methods, or should be documented accordingly.

**Comment by jameschapman19** [comment]
Thanks for spotting this. You're absolutely right. It's a throwback to when _CCA_Base inherited a different class and I just hadn't spotted the redundancy. Easy to fix though so will get this done 🤟

**Comment by jameschapman19** [comment]
Yeah been through and checked these all can't believe I didn't spot it before codecov will be delighted
