### ISSUE TITLE
weighted GCCA

### ISSUE THREAD

**Issue by 08tjlys** [jameschapman19/cca_zoo#14]
hi, 
   first of all, i wanna thank you for such great cca-family package. 
   i wonder for multiple views input like GCCA, now are we allowed to set different weights for different views input which may be quite common in practical use, for example some view is more important than others
   may we expect this in future release?
   paper mentioned such idea http://www.cs.jhu.edu/~mdredze/publications/2016_acl_multiview.pdf
 
   thanks again for your wonderful package

**Comment by jameschapman19** [comment]
Thanks for this idea. I've gone ahead and implemented it in the latest version 1.1.21 (both weighted views and observed/unobserved). For the moment I've just got the exact solution (i.e. directly changing the eigenvalue problem). I should be able to improve efficiency in the future by making a version that uses alternating least squares solvers so will leave this open.

**Comment by jameschapman19** [comment]
This particular case should now work by using GCCA().fit(view1,view2,...,view_n, view_weights=view_weights, K=K) where view_weights is an array with one weight for each view and K is an array with (n,N) where n is the number of views and N is the total number of samples and its entries are 1 or 0 depending if that sample is observed for that view

**Comment by jameschapman19** [comment]
small edit - slightly changed the way methods are built and constructed so the above is now GCCA(view_weights=view_weights, K=K).fit(view1,view2,...,view_n)
