### ISSUE TITLE
ImportError: cannot import name 'GridsearchCV' from 'cca_zoo.model_selection'

### ISSUE THREAD

**Issue by vignesh294** [jameschapman19/cca_zoo#142]
Hi, I am getting this error: ImportError: cannot import name 'GridsearchCV' from 'cca_zoo.model_selection' (/opt/anaconda3/lib/python3.8/site-packages/cca_zoo/model_selection/__init__.py)

on the statement:
ImportError: cannot import name 'GridsearchCV' from 'cca_zoo.model_selection' (/opt/anaconda3/lib/python3.8/site-packages/cca_zoo/model_selection/__init__.py)

Appreciate any help on this!

**Comment by jameschapman19** [comment]
Hm. Unhelpful error message. One thing is that I have never tested install on conda so it could be along those lines and therefore might be fixable using pip install within conda?

**Comment by jameschapman19** [comment]
From a quick google it looks likely it's something to do with pip install within conda e.g. this sort of thing: https://stackoverflow.com/questions/63650117/modulenotfounderror-or-importerror-when-installing-python-packages-to-conda-env

**Comment by vignesh294** [comment]
Thanks for getting back on this. I installed using pip and conda is not even installed in the system where I tried to run this. Will try looking into why it is installing anaconda3 folder. Thank you very much for your inputs!

**Comment by jameschapman19** [comment]
Does your closing this mean it

**Comment by jameschapman19** [comment]
This looks OK to me on colab - i'll await further info on this conda situation. I had a fiddle with making the package conda installable but haven't finished yet!
