### ISSUE TITLE
cannot import name 'architectures' from 'cca_zoo.deepmodels'

### ISSUE THREAD

**Issue by vignesh294** [jameschapman19/cca_zoo#143]
Hi James,

Thanks for this amazing framework! I am trying to learn and try out a number of CCA methods, but while trying out deep cca, I am getting this error: 

`cannot import name 'architectures' from 'cca_zoo.deepmodels' (/usr/local/lib/python3.7/dist-packages/cca_zoo/deepmodels/__init__.py)`

I installed cca_zoo as `pip install cca-zoo[all]`

Please let me know if you have any suggestions!

**Comment by jameschapman19** [comment]
So you still have this issue now but the other one is fixed?

This is more likely to be because you haven't got a working install of pytorch in the environment so try going through the installation instructions on the pytorch website

**Comment by vignesh294** [comment]
No it's not fixed, it's not important to do grid search currently so I need to pivot to this one as this is of very high priority right now. I installed pytorch and `pip list` lists this among many others:

`torch                         1.11.0+cu113
torchaudio                    0.11.0+cu113
torchmetrics                  0.9.0
torchsummary                  1.5.1
torchtext                     0.12.0
torchvision                   0.12.0+cu113`

However the error message hasn't changed. I am running on colab, appreciate any leads. Thanks!

**Comment by jameschapman19** [comment]
gotcha - useful to know it's colab - I'll have a look now :)

**Comment by jameschapman19** [comment]
Cool fixed this with v1.12.7

**Comment by vignesh294** [comment]
Thanks, it's fixed now.

Not directly related to this, but I am looking to understand the correlation between two time series data sets and understanding how the variables contribute to the overall correlation.

I have two sets each having two variables as:
`
X = [x1, x2] and Y = [y1,y2]
`

For now I tried using CCA as:
`cca = CCA(latent_dims=1).fit([X, Y])
X_transformed, Y_transformed = cca.transform([X, Y])
loadings = cca.get_loadings([X, Y])
correlation=cca.score([X,Y])
`

I am getting overall correlation Corr(X,Y) as 0.72 and relationships using loadings as:
`
X = 0.29 * x1 + 0.97 * x2
Y = 0.15 * y1 + 0.99 * y2
`
These results are in line with what results Sklearn CCA outputs on this data. Now, the thing with using CCA is that it is generic and not optimized for time series data. Would you mind suggesting any of the methods you have implemented for this case that is more optimal for time series data and can be used to find correlations and individual variables' contribution like how I have done with CCA? I understand Deep CCA works for most types of data and can be used to find non-linear correlations as well, but I am not able to find much document on how to fit and get the loadings.

I understand this page is for bugs and issues on the platform, would you mind recommending another platform I can reach you at and get you inputs?

Thanks!

**Comment by jameschapman19** [comment]
I've added my email to my GitHub profile - I'll reply to the above over there if you send it :)
