### ISSUE TITLE
cca_zoo.models.GRCCA.fit(groups) does not work together with cca_zoo.model_selection.GridSearchCV.fit(groups) 

### ISSUE THREAD

**Issue by JohannesWiesner** [jameschapman19/cca_zoo#149]
When passing `cca_zoo.models.GRCCA` as an estimator to `cca_zoo.model_selection.GridSearchCV` I think there's a variable naming conflict concerning `groups`. Whereas in `GridSearchCV`'s `.fit()` method the `group` keyword argument denotes **sample** groups, in `GRCCA`'s `.fit() `method `groups` is used to define **feature** subsets. As a consequence, the feature groups cannot be passed over to `GRCCA`  (which also leads to #148). 

I guess one solution would be to rename `GRCCA.fit(groups)` to something like `GRCCA.fit(feature_groups) `

Another solution would be to use the `__init__` method of `GRCCA` instead of providing the groups in the `.fit()` method by providing the feature subsets as `group1` and `group2` just as in the [original implementation](https://github.com/ElenaTuzhilina/RCCA/blob/849809093008365086028ccd8385958e0c871208/R/GRCCA.R#L80)

**Comment by JohannesWiesner** [comment]
Hi James, just noticed your latest commits and your changes to `GRCCA`. Not sure, but I think this is not right?  Shouldn't it be `feature_groups` instead of `sample_groups` and the [checking be done ](https://github.com/jameschapman19/cca_zoo/blob/4c10ceb82b920afbeae61cd744e784e447a09d23/cca_zoo/models/_prcca.py#L142-L156) on the columns instead of the rows?

**Comment by jameschapman19** [comment]
Feel free to take a look yourself - I definitely haven’t fixed either yet and am not claiming to have :) have had a busy week so can only take a look when I get the chance

**Comment by jameschapman19** [comment]
Right so the latest code is now looking pretty good for PRCCA and GRCCA. Have done a little bit of testing and they produce sensible outputs. Still left with the gridsearchCV problem so will need to have a think about how to achieve that.

A nice easter egg is that they have both extended to multiple views (beyond the 2 in the original work)! Just need a dataset to prove it all works and that's already something nice!

**Comment by jameschapman19** [comment]
I've got the idxs and feature_groups parameters in the fit method so it's neat at least but gridsearch doesn't seem to like kwargs with the fit method or at least wants something specific which I'll need to look into and slightly adapt my gridsearchCV (itself already an adaptation of sklearn gridsearchcv)

**Comment by JohannesWiesner** [comment]
> 've got the idxs and feature_groups parameters in the fit method so it's neat at least but gridsearch doesn't seem to like kwargs with the fit method or at least wants something specific which I'll need to look into and slightly adapt my gridsearchCV (itself already an adaptation of sklearn gridsearchcv)

Yeah, it's kind of weird, I've tried to play around with it, but I also couldn't manage to pass `feature_groups` over to `GRCCA()` when I use it in combination with `GridSeachCV`. I even tried to follow [this thread](https://stackoverflow.com/a/31082518/8792159)  and created a one-step `Pipeline` (which is kind of weird, because why would you create a pipeline if you only have one estimator...) but it also didn't work....

**Comment by JohannesWiesner** [comment]
In the mean time I created my own `gridsearchcv` function which can handle the additional `fit_params`

```python
def gridsearch_cv(estimator,X,y,cv,param_grid,n_jobs=1,pre_dispatch=1,**fit_params):

    # first create a list of dictionaries with all possible estimator
    # parameters
    param_grid = list(ParameterGrid(param_grid))

    def _fit_and_score(estimator,X,y,train_idx,test_idx,param_grid,**fit_params):
        
        # create a copy of the estimator for each iteration
        estimator_clone = clone(estimator)
        
        # create training and test folds
        X_train,X_test = X[train_idx,:],X[test_idx,:]
        y_train,y_test = y[train_idx,:],y[test_idx,:]
        
        # train each combination of parameters on the training fold
        # and evaluate the performance on the validation fold
        scores = []
        
        for params in param_grid:
            for key,value in params.items():
                estimator_clone.set_params(**params)
                
            estimator_clone.fit([X_train,y_train],**fit_params)
            correlations = estimator_clone.score([X_test,y_test])
            score = np.mean(correlations)
            scores.append(score)
    
        return scores
    
    # multiple gridsearches in parallel
    results = Parallel(n_jobs=n_jobs,pre_dispatch=pre_dispatch)(delayed(_fit_and_score)(estimator,X,y,train_idx,test_idx,param_grid,**fit_params) for train_idx,test_idx in cv.split(X))
    
    # create numpy array of results (n_folds x n_parameter_combinations)
    results = np.array(results)
    
    # find best parameter combinations
    best_idx = np.argmax(np.mean(results,axis=0))
    best_params = param_grid[best_idx]
    
    return best_params,results
```

The only problem here  that this function won't take care of view-wise parameters like `c=[0.1,0.2]` or something. Speaking of: I am not sure if `GRCCA` also allows for multi-view penalty settings? In the [docstring](https://cca-zoo.readthedocs.io/en/latest/api/models.html#cca_zoo.models.GRCCA) it says that both `c` and `mu` have to be floats but I didn't receive an error when I created an instance of `GRCCA` (e.g. `estimator = GRCCA(latent_dims=2,c=[0.1,0.2],mu=[0.2,0.3])` ?)

**Comment by JohannesWiesner** [comment]
@jameschapman19 : I think the bug lies [here](https://github.com/jameschapman19/cca_zoo/blob/e4537cc66b559e6662fc8f1ff6777fcb8c73a2c0/cca_zoo/model_selection/_search.py#L208)? When the user passes `groups` as input to `cca_zoo.model_selection.GridSearchCV` this never gets forwarded to `BaseSearchCV`. I think we could solved that by rewriting the line as:

```
self = BaseSearchCV.fit(self, np.hstack(X), y=y, groups=groups, **fit_params)
```

**Comment by JohannesWiesner** [comment]
Yup, works now, will send PR
