### ISSUE TITLE
How to install the deep learning component?

### ISSUE THREAD

**Issue by JackShi9** [jameschapman19/cca_zoo#153]
I have a Mac and when I try to install the deep learning components by 

`pip install cca-zoo[deep]`

it simply threw me a `zsh:no matches found` error.

**Comment by jameschapman19** [comment]
Sounds like a zsh thing. From this link:

https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity

It looks like you need to do something like:

`pip install 'cca-zoo[deep]'`

**Comment by JackShi9** [comment]
That worked, thanks a lot! Also, is there any documentation/example on how the models (like DCCAE) should be used? That'd be very helpful.

**Comment by jameschapman19** [comment]
Probably the best example at the moment is:

https://cca-zoo.readthedocs.io/en/latest/auto_examples/plot_dvcca.html#sphx-glr-auto-examples-plot-dvcca-py

But in the course of answering your question I've realised that at some point I've lost a 'how to build a compatible dataset' section. 

Will add something on this shortly but the gist is you need a pytorch dataset with a __getitem__ that returns at least "views":

def __getitem__(self, idx):
        # your code here
        return {"views": (view_1,view_2)}

**Comment by JackShi9** [comment]
Thank you for the quick reply, I will take a look (yeah I'm particularly curious about how to set up the datasets, etc.). I'd also love to chat sometime about your implementation. For example, I saw that (for DCCAE) you used the approach of maximizing the sum of singular values (which is the correlation) for the correlation loss. I'm wondering why not adding a linear layer at the end of the encoders for both views (let's assume we are dealing with 2 views for now) and minimize the distance between those linear embeddings (see [here](https://openaccess.thecvf.com/content_cvpr_2018/CameraReady/1124.pdf), section 3.1), which is equivalent to the singular value loss approach.

**Comment by jameschapman19** [comment]
If you ping me an email more than happy to have a discussion - incidentally the paper you linked to is DCCA_SDL in this package.

**Comment by jameschapman19** [comment]
And on singular value vs distance the answer is two-fold

a) because I'm just following the original paper!😅

b) because you need to enforce the orthogonality of components (at least implicitly). SDL achieves this by using the soft decorrelation loss so if that's big enough then the components will be orthogonal and you are justified in using the distance/frobenius norm

But I agree in principle that you could write something like the original DCCAE that had the stochastic decorrelation loss you cited.

**Comment by JackShi9** [comment]
> If you ping me an email more than happy to have a discussion - incidentally the paper you linked to is DCCA_SDL in this package.

Just sent you an email :)

**Comment by JackShi9** [comment]
> And on singular value vs distance the answer is two-fold
> 
> a) because I'm just following the original paper!😅
> 
> b) because you need to enforce the orthogonality of components (at least implicitly). SDL achieves this by using the soft decorrelation loss so if that's big enough then the components will be orthogonal and you are justified in using the distance/frobenius norm
> 
> But I agree in principle that you could write something like the original DCCAE that had the stochastic decorrelation loss you cited.

a) Makes sense haha 

b) I agree, the batch size in SDL needs to be big enough, but they also have the stochastic accumulation thing that should help

**Comment by jameschapman19** [comment]
Played around this morning updating some of the data stuff.

here's a new tutorial on using your own datasets:

https://cca-zoo.readthedocs.io/en/latest/auto_examples/plot_dcca_custom_data.html#sphx-glr-auto-examples-plot-dcca-custom-data-py

I'll close the issue as I think that's the relevant issues solved!

**Comment by JackShi9** [comment]
Thanks so much James!
