### ISSUE TITLE
torch error while trainning DCCA and DCCAE  

### ISSUE THREAD

**Issue by Umaruchain** [jameschapman19/cca_zoo#159]
Hi! Dear author, I really appreciate your excellent job! 
I am training DCCA and DCCAE with random data, but such problems always occur after some epochs.
Do you have any ideas about it?
My torch version is 1.12.0 +cu 11.6
torch.linalg.eigh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 597).

**Comment by jameschapman19** [comment]
Couple of options:

It could be related to this (https://github.com/pytorch/pytorch/issues/75391) in which case it's a cuda problem.

Alternatively check that batch size is greater than the latent dimensions (ideally much greater).

Another alternative is to check out DCCA_EigenGame (bit of a shameless plug for my work) - an alternative way to optimise DCCA that doesn't use linalg.eig in the objective and is pretty effective for smaller batch sizes, or DCCA_NOI - designed for similar case but has a couple of hyperparameters.

**Comment by Umaruchain** [comment]
Thanks!!!! I will try to increase the batch size and your model!!
