### ISSUE TITLE
Why we have to conduct linear cca before we count the score of projected embedding?

### ISSUE THREAD

**Issue by Umaruchain** [jameschapman19/cca_zoo#160]
Dear author,
I am very interested in your great work. But I am confused about the Score API.  When I use DCCA, I want to use the projected embedding as the output. However, when I calculate the corrcoef between the embeddings directly, the score is really small. And I find that you will add a linear CCA before the Score API, could you please explain this problem?

**Comment by jameschapman19** [comment]
Basically the original Deep CCA (Andrew 2013) technically doesn't find the projections themselves but finds encodings which if you applied a linear CCA to them would have highly correlations.

One way to think about this is that DCCA is like a preprocessing step before a CCA.

You can see this in the examples page where I compare some of the DCCA methods and plot their latent representations.

https://cca-zoo.readthedocs.io/en/latest/auto_examples/plot_dcca.html#sphx-glr-auto-examples-plot-dcca-py

**Comment by Umaruchain** [comment]
Thanks for your reply!!  Yes, the original deep cca needs a linear cca layer. Have you tried to compare the representations with/without linear cca?  In my experiment, as for downstream tasks, the results seem the same, the only thing that changes is the score. By the way, do you think changing the loss objective to make the correlation matrix like linear cca is a good method? You know, in this way, those scores between views can be obtained directly.

**Comment by Umaruchain** [comment]
Thank you so much!!! I have understood that the linear cca is just a transformation layer and it is not necessary for deep models to use it since it would not change the quality of my representations (I just want a metric to tell how close these embeddings are). I will try to run some new cca methods as you mentioned.
Thanks again for your generous help, your code is comfortable to read and it is a great accomplishment.

**Comment by Umaruchain** [comment]
Yes, I make several groups of embeddings and I want to find a method to find the correlation adaptively. For example, two views are born to be unrelated and, the dcca methods will always try to maximize the correlation, which results in poor performance in downstream tasks, but linear cca remains robust. I want to find a way to keep this property.
