### ISSUE TITLE
problem of latent_dims setting of DCCA_EigenGame

### ISSUE THREAD

**Issue by Umaruchain** [jameschapman19/cca_zoo#168]
Dear James,
I am reviewing your exciting job- DCCA_EigenGame and I am confused about some problems. 
1. Here is the code of your DCCA_EigenGame. 
     When zi. shape[1]==self.latent_dims, this always produces an empty matrix. Is this correct?
      A += torch.cov(torch.hstack((zi, zj)).T)[self.latent_dims :, : self.latent_dims]

2. In your paper(A GENERALIZED EIGENGAME WITH EXTENSIONS TO DEEP MULTIVIEW REPRESENTATION LEARNING)
 around the formula 40, you define Afg, Bfg and it seems that Afg@ Bfg always be zero matrix. So I am confused about the meaning of Afg@Bfg in formula 41.

Thanks again for your sincere help.

**Comment by Umaruchain** [comment]
Dear James,
Could you please help me clarify my doubts? I am wondering if I have made any obvious mistakes or if my expressions are not clear enough. If you could spare some time to answer my questions, I would be extremely grateful.

In addition, we previously discussed scheduling a chat, but I haven't received an email from you. It's possible that I missed it. Would you mind sharing your email with me so we can arrange a time to chat?

**Comment by jameschapman19** [comment]
Hi

1. No. To me this seems obvious so is difficult to explain. A is latent_dimsxlatent_dims. We extract latent_dimsxlatent_dims matrices from bigger covariance matrices because torch.cov defaults to giving both within view and between view covariance.

**Comment by jameschapman19** [comment]
You could definitely convince yourself of this with the debugger

**Comment by jameschapman19** [comment]
2. Important: I have updated the code but not yet the paper so that A in the code is equal to A+B in the paper for CCA. This ensures that A is positive semi definite and improved convergence.

**Comment by jameschapman19** [comment]
Will respond to your email next week when I'm back in the office!

**Comment by Umaruchain** [comment]
Looking forward to hear from you！！！
Thanks again for your help
