### ISSUE TITLE
the problem of the model.transform()

### ISSUE THREAD

**Issue by baili119** [jameschapman19/cca_zoo#169]
![image](https://user-images.githubusercontent.com/114966227/228168037-89614a6b-677c-4c70-ab27-4b4f7646264c.png)

Traceback (most recent call last):
  File "D:\anacodan\envs\my_first_env\lib\site-packages\cca_zoo\deepmodels\_base.py", line 86, in transform
    views = [view.to(self.device) for view in batch["views"]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by baili119** [comment]
the input of DCCA.fit_transform() is a list of the nadarray type(sample ,feature) about the handwritten dataset which has 6 views.
Dear James：
         This is my first time discussing on github, and if my way of speaking is not very standard, I would like to say sorry to you and will gradually improve after that.

**Comment by jameschapman19** [comment]
Hi 👋 

No problem at all and thanks for getting in touch.

Basically the deep models take data loaders as input not numpy arrays. One of the examples in the docs shows how to use numpy arrays with deep models - basically I have a helper class that transforms list of numpy views to data loader. Let me know if you need more help - I agree this is a tiny bit confusing because the normal models take lists of numpy arrays but it felt slightly cleaner in the end doing it this way.

**Comment by baili119** [comment]
Dear James:

Thank you very much for your reply, which made me feel warm and helped me point me in the direction of solving the problem.😊😊

Since my current research direction is fuzzy system TSK, I am currently trying to integrate the multi-view direction. Could you teach me to write an example: Extract features of a multi-view dataset such as handwritten using DCCA in CCA-ZOO?

**Comment by baili119** [comment]
Dear James:

Thank you very much for your guidance, numpy can be turned into a dataloader using a helper class.

`from cca_zoo.data.deep import NumpyDataset
from cca_zoo.data.deep import check_dataset
from cca_zoo.data.deep import get_dataloaders
data_dict=NumpyDataset(data)
check_dataset(data_dict)
dataloader=get_dataloaders(data_dict,batch_size=200,shuffle_train=True)`

**Comment by baili119** [comment]
Dear James:

Thank you very much for your guidance, numpy can be turned into a dataloader using a helper class.

```
from cca_zoo.data.deep import NumpyDataset
from cca_zoo.data.deep import check_dataset
from cca_zoo.data.deep import get_dataloaders

data_dict=NumpyDataset(data)
check_dataset(data_dict)
dataloader=get_dataloaders(data_dict,batch_size=200,shuffle_train=True)
```
