### ISSUE TITLE
Could you provide a 3-group CCA method?

### ISSUE THREAD

**Issue by WantongLi123** [jameschapman19/cca_zoo#174]
Thank you for such a nice synthesis of CCA methods.
Could you provide a 3-group CCA method?
Please check equation(25) in https://doi.org/10.1016/0305-0548(95)00067-4

**Comment by jameschapman19** [comment]
MCCA should be exactly equation 25

Most of the methods can be used with more than 2 views (my term)/groups (your term)/datasets (the term from the paper you shared).

**Comment by WantongLi123** [comment]
Excellent! Thanks
