### ISSUE TITLE
torch._C._LinAlgError: torch.linalg.solve: The solver failed because the input matrix is singular.

### ISSUE THREAD

**Issue by Wolongchicken** [jameschapman19/cca_zoo#194]
Hello, I am trying to use DGCCA to fuse the PCC and PLV features calculated from EEG samples, but I frequently report errors: torch_ C. LinAlgError: torch. final. solve: The solver failed because the input matrix is singular.

**Comment by jameschapman19** [comment]
Can't use that objective if batch size isn't much bigger than number of latents.

Use our CCA-EY objective it is designed for this scenario.

**Comment by Wolongchicken** [comment]
I'm sorry, but after switching to CCA-EY, a new error occurred:
`Trainer.fit` stopped: No training batches. , and I found that I am currently unable to resolve it.

**Comment by jameschapman19** [comment]
Could you share a code snippet?

**Comment by Wolongchicken** [comment]
Thank you for your patient answer. This is a part of the current code.    
    
    dataset = NumpyDataset([train_pcc_tensor.numpy(), train_plv_tensor.numpy()], batch_size=load_batch_size)
    val_dataset = NumpyDataset([test_pcc_tensor.numpy(), test_plv_tensor.numpy()], batch_size=load_batch_size)
    train_loader, val_loader = get_dataloaders(dataset=dataset, val_dataset=val_dataset, batch_size=load_batch_size, shuffle_train=True)

    LATENT_DIMS = 64
    # number of layers with nodes in each one
    layer_sizes1 = [256, 512, 128, LATENT_DIMS] 
    layer_sizes2 = [256, 512, 128, LATENT_DIMS]  

    encoder_1 = MlpNet(layer_sizes1, train_pcc_tensor.shape[-1])
    encoder_2 = MlpNet(layer_sizes2, train_plv_tensor.shape[-1])

    encoder_1.apply(init_weights_ByXavier)
    encoder_2.apply(init_weights_ByXavier)

    dcca = DCCA(latent_dimensions=LATENT_DIMS, encoders=[encoder_1, encoder_2], lr=1e-3, max_epochs=1000，objectives=objectives._CCA_EYLoss)
    dcca.to(device)

    print('Begin DCCA Tarining')
    start = time.time()

    checkpoint_callback = ModelCheckpoint(
        dirpath='../CCAzoo/weights',
        filename='dgcca-{epoch:04d}-{train/objective:.4f}',
        save_top_k=1,
        verbose=True,
        monitor="train/objective",
        mode='min'
    )

    progress_bar = ProgressBar()
    trainer_dcca = pl.Trainer(
        max_epochs=EPOCHS,
        enable_checkpointing=True,
        enable_model_summary=False,
        enable_progress_bar=True,
        callbacks=[checkpoint_callback, progress_bar],
        check_val_every_n_epoch=1
    )
    trainer_dcca.fit(dcca, train_loader, val_loader)

    end = time.time()
    print(f"{end - start}s")
    print('Finished DCCA Tarining')

**Comment by Wolongchicken** [comment]
Thank you for your patient answer. This is a part of the current code.    
    
    dataset = NumpyDataset([train_pcc_tensor.numpy(), train_plv_tensor.numpy()], batch_size=load_batch_size)
    val_dataset = NumpyDataset([test_pcc_tensor.numpy(), test_plv_tensor.numpy()], batch_size=load_batch_size)
    train_loader, val_loader = get_dataloaders(dataset=dataset, val_dataset=val_dataset, batch_size=load_batch_size, shuffle_train=True)

    LATENT_DIMS = 64
    # number of layers with nodes in each one
    layer_sizes1 = [256, 512, 128, LATENT_DIMS] 
    layer_sizes2 = [256, 512, 128, LATENT_DIMS]  

    encoder_1 = MlpNet(layer_sizes1, train_pcc_tensor.shape[-1])
    encoder_2 = MlpNet(layer_sizes2, train_plv_tensor.shape[-1])

    encoder_1.apply(init_weights_ByXavier)
    encoder_2.apply(init_weights_ByXavier)

    dcca = DCCA(latent_dimensions=LATENT_DIMS, encoders=[encoder_1, encoder_2], lr=1e-3, max_epochs=1000，objectives=objectives._CCA_EYLoss)
    dcca.to(device)

    print('Begin DCCA Tarining')
    start = time.time()

    checkpoint_callback = ModelCheckpoint(
        dirpath='../CCAzoo/weights',
        filename='dgcca-{epoch:04d}-{train/objective:.4f}',
        save_top_k=1,
        verbose=True,
        monitor="train/objective",
        mode='min'
    )

    progress_bar = ProgressBar()
    trainer_dcca = pl.Trainer(
        max_epochs=EPOCHS,
        enable_checkpointing=True,
        enable_model_summary=False,
        enable_progress_bar=True,
        callbacks=[checkpoint_callback, progress_bar],
        check_val_every_n_epoch=1
    )
    trainer_dcca.fit(dcca, train_loader, val_loader)

    end = time.time()
    print(f"{end - start}s")
    print('Finished DCCA Tarining')

**Comment by Wolongchicken** [comment]
Thank you for your patient answer. This is a part of the current code.    
    
    dataset = NumpyDataset([train_pcc_tensor.numpy(), train_plv_tensor.numpy()], batch_size=load_batch_size)
    val_dataset = NumpyDataset([test_pcc_tensor.numpy(), test_plv_tensor.numpy()], batch_size=load_batch_size)
    train_loader, val_loader = get_dataloaders(dataset=dataset, val_dataset=val_dataset, batch_size=load_batch_size, shuffle_train=True)

    LATENT_DIMS = 64
    # number of layers with nodes in each one
    layer_sizes1 = [256, 512, 128, LATENT_DIMS] 
    layer_sizes2 = [256, 512, 128, LATENT_DIMS]  

    encoder_1 = MlpNet(layer_sizes1, train_pcc_tensor.shape[-1])
    encoder_2 = MlpNet(layer_sizes2, train_plv_tensor.shape[-1])

    encoder_1.apply(init_weights_ByXavier)
    encoder_2.apply(init_weights_ByXavier)

    dcca = DCCA(latent_dimensions=LATENT_DIMS, encoders=[encoder_1, encoder_2], lr=1e-3, max_epochs=1000，objectives=objectives._CCA_EYLoss)
    dcca.to(device)

    print('Begin DCCA Tarining')
    start = time.time()

    checkpoint_callback = ModelCheckpoint(
        dirpath='../CCAzoo/weights',
        filename='dgcca-{epoch:04d}-{train/objective:.4f}',
        save_top_k=1,
        verbose=True,
        monitor="train/objective",
        mode='min'
    )

    progress_bar = ProgressBar()
    trainer_dcca = pl.Trainer(
        max_epochs=EPOCHS,
        enable_checkpointing=True,
        enable_model_summary=False,
        enable_progress_bar=True,
        callbacks=[checkpoint_callback, progress_bar],
        check_val_every_n_epoch=1
    )
    trainer_dcca.fit(dcca, train_loader, val_loader)

    end = time.time()
    print(f"{end - start}s")
    print('Finished DCCA Tarining')

**Comment by jameschapman19** [comment]
Hi,

I'm a bit confused by this one.

That being said I have just published a new version of the package that takes away the somewhat ugly:

```
dcca = DCCA(latent_dimensions=LATENT_DIMS, encoders=[encoder_1, encoder_2], lr=1e-3, max_epochs=1000，objectives=objectives._CCA_EYLoss)
```

So that now each DCCA method is its own class e.g.

```
dcca = DCCA_EY(latent_dimensions=LATENT_DIMS, encoders=[encoder_1, encoder_2], lr=1e-3, max_epochs=1000)
```

Which might reduce some bugs.

**Comment by Wolongchicken** [comment]
Thank you for your patient answer.
