### ISSUE TITLE
Question about the removal of the c argument in SCCA_PMD function in version 1.16.6

### ISSUE THREAD

**Issue by BogyeomKim** [jameschapman19/cca_zoo#197]
Hi,

I am currently using version 1.16.6 of the cca-zoo package and have encountered an issue with the SCCA_PMD function. It seems that the c argument, which was previously supported, is no longer available.

Could you please provide some clarification on this? Specifically:

What was the purpose of the c argument in the earlier versions?
Has this argument been replaced by a different one, and if so, what should I use instead?
I appreciate your help and look forward to your guidance on how to proceed.

Thank you for your time and assistance.

Best regards,
Bogyeom Kim

**Comment by jameschapman19** [comment]
now called Tau (same meaning as in the witten paper) - I was using c elsewhere to represent ridge regularisation and felt it more confusing to a new user to have mixed meaning.
