### ISSUE TITLE
RuntimeError: symeig_cpu: the algorithm failed to converge; 149 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.

### ISSUE THREAD

**Issue by star0511** [jameschapman19/cca_zoo#35]
When I run the following code, I get the above error

import numpy as np
from torch import optim
from cca_zoo import data
import scipy.io as sio
from cca_zoo.deepmodels import DCCA, DCCAE, DVCCA, DCCA_NOI, DTCCA, SplitAE, DeepWrapper
from cca_zoo.deepmodels import objectives, architectures
X = np.random.rand(2000, 2048)
Y = np.random.rand(2000, 2048)
latent_dims = 150
device = 'cpu'
encoder_1 = architectures.Encoder(latent_dims=latent_dims, feature_size=2048)
encoder_2 = architectures.Encoder(latent_dims=latent_dims, feature_size=2048)
# DCCA
dcca_model = DCCA(latent_dims=latent_dims, encoders=[encoder_1, encoder_2],
                  objective=objectives.CCA)
# hidden_layer_sizes are shown explicitly but these are also the defaults
dcca_model = DeepWrapper(dcca_model, device=device)
dcca_model.fit((X, Y), epochs=10)

**Comment by jameschapman19** [comment]
Hi,

I've taken a look at this this morning and found where the problem starts to appear. 

From the pytorch docs @ https://pytorch.org/docs/stable/generated/torch.linalg.eig.html#torch.linalg.eig:

Gradients computed using V will only be finite when A does not have repeated eigenvalues. Furthermore, if the distance between any two eigenvalues is close to zero, the gradient will be numerically unstable

I'm taking a look now to see if there's any engineering fixes. 

Your example should work for some number of latent dimensions (when I tried it works up to ~110)

**Comment by jameschapman19** [comment]
New version using pytorch 1.9 should work for this problem (cca-zoo 1.7.1)

**Comment by jameschapman19** [comment]
So now the objectives run off torch.linalg.eigvals which is stable when eigenvalues are the same. I'm going to tentatively close the issue and thanks @star0511 for motivating me to finding a fix (and to the pytorch developers for adding torch.linalg.eigvals!)

**Comment by jameschapman19** [comment]
I've also added a test for exactly this example up to 250 latent dimensions :)
