### ISSUE TITLE
Adapting to numpy convention for random state setting

### ISSUE THREAD

**Issue by htwangtw** [jameschapman19/cca_zoo#36]
Currently to get consistent numerical results, one needs to set a global random seed, as there's no random state parameter in the CCA classes.
It will greatly improve the numerical output consistency adding a parameter for random state.

It will also worth it to make sure the implementation is up-to-date with the latest best practice suggested by numpy.
The current example will not be supported after 1.16, see: https://numpy.org/doc/stable/reference/random/legacy.html
More discussion about the new best practice: 
https://numpy.org/neps/nep-0019-rng-policy.html
https://albertcthomas.github.io/good-practices-random-number-generators/

**Comment by jameschapman19** [comment]
Fixed this with #44. Looks like scikit-learn with all models having random_state parameter. Results are reproducible when this parameter is not None
