### ISSUE TITLE
RuntimeError: expected scalar type Double but found Float

### ISSUE THREAD

**Issue by DiegoMac17** [jameschapman19/cca_zoo#49]
When running the tutorial Fashion MINST examples of Deep CCA, the error "RuntimeError: expected scalar type Double but found Float" appears in the training phase. Moreover when running the DCCAE example the same errors is thrown for the dcca_model.predict_corr function. The last part of the error seems to be due to some Torch problem.

~\AppData\Local\Temp/ipykernel.py in <module>
     13 
     14 dccae_results = np.stack(
---> 15     (dccae_model.train_correlations[0, 1], dccae_model.predict_corr(test_dataset)[0, 1]))

~\anaconda3\envs\CCA\lib\site-packages\cca_zoo\deepmodels\deepwrapper.py in predict_corr(self, test_dataset, train, batch_size)
    191         :return: numpy array containing correlations between each pair of views for each dimension (#views*#views*#latent_dimensions)
    192         """
--> 193         transformed_views = self.transform(test_dataset, train=train, batch_size=batch_size)
    194         all_corrs = []
    195         for x, y in itertools.product(transformed_views, repeat=2):

~\anaconda3\envs\CCA\lib\site-packages\cca_zoo\deepmodels\deepwrapper.py in transform(self, test_dataset, test_labels, train, batch_size)
    209             for batch_idx, (data, label) in enumerate(test_dataloader):
    210                 data = [d.to(self.device) for d in list(data)]
--> 211                 z = self.model(*data)
    212                 if batch_idx == 0:
    213                     z_list = [z_i.detach().cpu().numpy() for i, z_i in enumerate(z)]

~\anaconda3\envs\CCA\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

................................

~\anaconda3\envs\CCA\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     94 
     95     def forward(self, input: Tensor) -> Tensor:
---> 96         return F.linear(input, self.weight, self.bias)
     97 
     98     def extra_repr(self) -> str:

~\anaconda3\envs\CCA\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1845     if has_torch_function_variadic(input, weight):
   1846         return handle_torch_function(linear, (input, weight), input, weight, bias=bias)
-> 1847     return torch._C._nn.linear(input, weight, bias)
   1848 
   1849

**Comment by jameschapman19** [comment]
Thanks for this! I believe I have just fixed it in latest version 1.7.10. Basically I switched the models to run double precision by default when using the DeepWrapper class (this helps with some stability issues e.g. #39). As you have noticed this wasn't compatible with the MNIST datasets which gave floats.

- I have now changed DeepWrapper to put things in double before passing to the model. 
- Have also added a test that runs a subset of the tutorial to check it runs

Your comment also raised a different issue which was that the reconstruction loss in the autoencoder was reduce='sum' which is bigger with larger batch size so needs more tuning of learning rate.

- Have changed this to reduce='mean' which produces much more sensible losses and convergence for DCCAE and SplitAE

**Comment by jameschapman19** [comment]
Note - when running the notebook again you may need to run: 

`!pip install cca-zoo[deep,probabilistic] --upgrade`

To get the new version :)

**Comment by jameschapman19** [comment]
I have uploaded a new run of the tutorial which seems to run OK so tentatively closing this but let me know if further issues

**Comment by DiegoMac17** [comment]
Thank you @jameschapman19 ! That was fast!  It is all working great now.
Also thank you for the AE 'reduce' parameter fix, it definitely achieves much more reasonable losses.
