### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by AdirRahamim** [jameschapman19/cca_zoo#71]
Hi,

I tried to use DCCA with the DeepWrapper module however I got the error mentioned above. I tried to use the supplied test script under test/test_deepmodels.py however I get the same error. The error arises while calculating the loss on line 160 in deepwrapper.py script.
Can you please check what makes this bug?

**Comment by jameschapman19** [comment]
From a quick google of this error (I can't replicate without perhaps more info on versions of pytorch?) it looks like it might relate to mixing floats and doubles.

Depending on your use case take a look at the pytorch-lightning branch where I have written a new training loop wrapper using pytorch-lightning which leverages all of their behind the scenes stuff with device and data management and is a much preferable option to my inflexible wrapper!

**Comment by AdirRahamim** [comment]
Hi, I work with PyTorch version 1.8.0, it's very strange that it works for you and I keep getting this bag. For some reason, it has a problem with the gradient calculation.

**Comment by AdirRahamim** [comment]
After finding the bug reason, and reading the following issue:https://github.com/pytorch/pytorch/pull/57189, the problem was solved with the update of PyTorch to a newer version.
Thank you for your help!

**Comment by jameschapman19** [comment]
Ah thanks for hunting this down! Will reopen this as a Reminder to myself to change the requirements to specify this version of torch.
