### ISSUE TITLE
Bad usage of exception handling in test

### ISSUE THREAD

**Issue by htwangtw** [jameschapman19/cca_zoo#73]
https://github.com/jameschapman19/cca_zoo/blob/0d7df3952bd86c96d33c0f03d910d6f10dc9e7c2/cca_zoo/test/test_models.py#L293-L295

A better way to handle this kind of case, see:
https://docs.pytest.org/en/latest/how-to/skipping.html#id1

**Comment by jameschapman19** [comment]
This is now fixed - thanks for the tip
