### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by jameschapman19** [jameschapman19/cca_zoo#76]
Reduce the dimensionality of the tests substantially. Add in some hard checks such as correlation thresholds where they are missing.

**Comment by jameschapman19** [comment]
Satisfied with this too. Tests still take a little while but I think they are now minimal and important (in the sense of checking crucial things ran) whereas before they were neither minimal nor all important

**Comment by emdupre** [comment]
This is great, thank you @jameschapman19 ! Would you say that with closing this you've addressed all of the reviewer feedback ? I see that #122 is open and currently failing tests, so I'm not sure if you were planning to work on that first.

Please just ping into the JOSS issue whenever you're ready, and I'll make sure that this gets to the reviewers !

**Comment by jameschapman19** [comment]
Yep - I'll check out what's going on with #122 and ping the issue - thanks :)
