### ISSUE TITLE
[JOSS Review] - CCA_Tutorial notebook produces errors on fresh install

### ISSUE THREAD

**Issue by ejolly** [jameschapman19/cca_zoo#77]
Including this here as part of my [JOSS review](https://github.com/openjournals/joss-reviews/issues/3823):

Looks like the first notebook produces errors in the following sections. These can also been seen in the notebook cell outputs if opening in Google Collab. Building tutorial notebook as part of your CI might be a helpful way to catch these and other issues in the future:

  -  The "Overfitting and Sample Size" section produces an error:  `rCCA object has no attribute scores`
  - The "Ridge Regularised CCA: from CCA to PLS produces an error: `Expected 2D array, got 1D array instead`
  - The "Regularised CCA" under the neuroimaging example also produces a `rCCA object has no attribute scores`

**Comment by jameschapman19** [comment]
As I mentioned in #75 I have followed all reviewers suggestions and put tutorials in sphinx-gallery so they are tested (and look great!)

Thanks again for the suggestion and something new I have learnt.
